"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 5, 3]
linemode = "size"
show_hidden = true
show_symlink = true
sort_by = "natural"
mouse_events = ["click", "scroll"]
title_format = "Yazi: {cwd}"

[preview]
wrap = "yes"
max_width = 1500
max_height = 1500

[input]
cursor_blink = true

[opener]
edit = [
	{ run = '${EDITOR} "$@"', desc = "$EDITOR", block = true },
	{ run = 'code "$@"', orphan = true },
]
play = [
	{ run = 'mpv "$@"' },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
extract = [
	{ run = '7z x -o"$(echo "${1%.*}")" "$1"', desc = "Extract here", for = "unix" },
]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]

[open]
prepend_rules = [{ "name" = "*.zip", use = "extract" }]

[plugin]
prepend_preloaders = [{ name = "/home/jade/mnt/mepic/**", run = "noop" }]
prepend_fetchers = [
	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },
]
